
The following have been reloaded with a version change:
  1) FFTW/3.3.8-gompic-2019b => FFTW/3.3.8-gompi-2019b
  2) OpenMPI/3.1.4-gcccuda-2019b => OpenMPI/3.1.4-GCC-8.3.0
  3) ScaLAPACK/2.0.2-gompic-2019b => ScaLAPACK/2.0.2-gompi-2019b
  4) SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4 => SciPy-bundle/2019.10-foss-2019b-Python-3.7.4


The following have been reloaded with a version change:
  1) SciPy-bundle/2019.10-foss-2019b-Python-3.7.4 => SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4

2020-05-21 12:30:31.457052: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Process Process-1:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./use_Combined.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "./use_Combined.py", line 723, in MCDO
    method_main()
  File "./use_Combined.py", line 656, in method_main
    (x_train, y_train), (x_test, y_test) = load_hdf5_dataset(DATA_PATH)
NameError: free variable 'DATA_PATH' referenced before assignment in enclosing scope
Process Process-2:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./use_Combined.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "./use_Combined.py", line 889, in MCBN
    method_main()
  File "./use_Combined.py", line 805, in method_main
    (x_train, y_train), (x_test, y_test) = load_hdf5_dataset(DATA_PATH)
NameError: free variable 'DATA_PATH' referenced before assignment in enclosing scope
Process Process-3:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./use_Combined.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "./use_Combined.py", line 1020, in Ensemble
    method_main()
  File "./use_Combined.py", line 962, in method_main
    print("Dataset_name: {}, N_folders: {}, total mebers: {}".format(DATANAME, N_FOLDERS, sum(N_ENSEMBLE_MEMBERS)))
NameError: free variable 'N_FOLDERS' referenced before assignment in enclosing scope
Process Process-4:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "./use_Combined.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "./use_Combined.py", line 1291, in VarianceOutput
    method_main()
  File "./use_Combined.py", line 1212, in method_main
    (x_train, y_train), (x_test, y_test) = load_hdf5_dataset(DATA_PATH)
NameError: free variable 'DATA_PATH' referenced before assignment in enclosing scope


###############################################################################
Peregrine Cluster
Job 11645101 for user 's2934833'
Finished at: Thu May 21 12:30:42 CEST 2020

Job details:
============

Name                : CombTest
User                : s2934833
Partition           : gpu
Nodes               : pg-gpu18
Cores               : 12
State               : COMPLETED
Submit              : 2020-05-21T09:44:07
Start               : 2020-05-21T12:30:23
End                 : 2020-05-21T12:30:42
Reserved walltime   : 02:00:00
Used walltime       : 00:00:19
Used CPU time       : 00:00:06 (efficiency:  2.73%)
% User (Computation): 72.35%
% System (I/O)      : 27.65%
Mem reserved        : 32000M/node
Max Mem used        : 0.00  (pg-gpu18)
Max Disk Write      : 0.00  (pg-gpu18)
Max Disk Read       : 0.00  (pg-gpu18)
Average GPU usage   : 0.0% (pg-gpu18)


Acknowledgements:
=================

Please see this page for information about acknowledging Peregrine in your publications:

https://wiki.hpc.rug.nl/peregrine/additional_information/scientific_output

################################################################################
